name: Build per Platform

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target_platform:
        required: true
        type: string
      executable_suffix:
        required: true
        type: string
      python_platform_tag:
        required: true
        type: string
      runs-on_value:
        required: true
        type: string
      revision:
        required: false
        type: string
        default: ${{ github.sha }}
      catboost_package_name:
        required: false
        type: string
        default: catboost_dev
      catboost_package_version:
        required: false
        type: string
        default: ''   # version from repository will be used
      artifacts_version:
        required: false
        type: string
        default: ${{ github.sha }}
      artifact_retention_days:
        required: false
        type: number
        default: 3

jobs:
  build:
    runs-on: ${{ inputs.runs-on_value }}
    env:
      CATBOOST_PACKAGE_NAME: ${{ inputs.catboost_package_name }}
      CATBOOST_PACKAGE_VERSION: ${{ inputs.catboost_package_version }}
      CMAKE_BUILD_CACHE_DIR: cmake_build_cache
    steps:
      - name: Get short SHA
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true
          echo "GITHUB_SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

      - if: inputs.os == 'linux'
        name: Checkout actions from catboost
        uses: actions/checkout@v4
        with:
          path: actions_from_catboost
          sparse-checkout: .github
          fetch-depth: 0

      #- name: Check global disk space
      #  run: df -h

      - if: inputs.os == 'linux'
        name: 'Maximize build space: stage 1'
        # Remove packages & tools cache not covered by easimon/maximize-build-space action
        uses: ./actions_from_catboost/.github/actions/build_linux_docker_cleanup_unneeded

      #- name: List packages by installed size
      #  run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n

      #- name: Check global disk space after stage 1
      #  run: df -h

      - name: Check disk space at root after stage 1
        run: |
          echo '------------usr'
          sudo du -hcd 1 /usr/local/
          sudo du -hcd 1 /usr/lib/
          sudo du -hcd 1 /usr/share/
          echo '------------opt'
          sudo du -hcd 1 /opt/pipx/
          sudo du -hcd 1 /opt/microsoft/
          echo '------------home'
          sudo du -hcd 1 /home/


      # - if: inputs.os == 'linux'
      #   name: 'Maximize build space: stage 2'
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 48500  # needed for docker image
      #     swap-size-mb: 1024
      #     remove-dotnet: 'true'
      #     remove-android: 'true'
      #     remove-haskell: 'true'
      #     remove-codeql: 'true'
      #     remove-docker-images: 'true'
