name: Check

on:
  push:
    branches:
      - R_staged_install_debug

jobs:
  check:
    name: Check per OS
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-13, macos-14, windows-2022]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: 'release'
      - run: Rscript -e 'print("hello")'
