name: Check build and tests per OS

on:
  workflow_call:
    inputs:
      runs-on_value:
        required: true
        type: string
      revision:
        required: false
        type: string
        default: ${{ github.sha }}
      catboost_package_name:
        required: false
        type: string
        default: catboost_dev
      catboost_package_version:
        required: false
        type: string
        default: ''   # version from repository will be used
      artifacts_version:
        required: false
        type: string
        default: ${{ github.sha }}
      artifact_retention_days:
        required: false
        type: number
        default: 3

jobs:
  test_xcode_select:
    runs-on: ${{ inputs.runs-on_value }}
    steps:
      - run: |
          #sudo xcode-select -s /Applications/Xcode_16.2.app
          export DEVELOPER_DIR=/Applications/Xcode_16.2.app
          clang --version

#  build:
#    name: Build
#    uses: ./.github/workflows/build_per_os.yaml
#    with:
#      runs-on_value: ${{ inputs.runs-on_value }}
#      revision: ${{ inputs.revision }}
#      catboost_package_name: ${{ inputs.catboost_package_name }}
#      catboost_package_version: ${{ inputs.catboost_package_version }}
#      artifacts_version: ${{ inputs.artifacts_version }}
#      artifact_retention_days: ${{ fromJSON(inputs.artifact_retention_days) }}

