name: Check

on:
  push:
    branches:
      - R_staged_install_debug

jobs:
  check:
    name: Check per OS
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-13, macos-14, windows-2022]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: 'release'
      - name: CatBoost installation
        shell: python
        run: |
          import platform
          import sys
          from subprocess import check_call

          def get_native_platform_name():
              system_name = 'windows' if sys.platform == 'win32' else sys.platform
              arch = platform.machine()
              if arch == 'AMD64':
                  arch = 'x86_64'
                  return system_name + '-' + arch

          platform_name = get_native_platform_name()
          print(f"platform_name={platform_name}")

          check_call(f"R -e \"install.packages('remotes')\"", shell=True)
          check_call(f"R -e \"remotes::install_url('https://github.com/catboost/catboost/releases/download/v1.2.7/catboost-R-{platform_name}-1.2.7.tgz', INSTALL_opts = c('--no-multiarch', '--no-test-load'))\"", shell=True)


