name: Check build and tests

on:
  push:
    branches:
      - github_actions_debug

jobs:
  check:
    name: Check per OS
    strategy:
      matrix:
        os: [windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'macos-13'
        name: on macOS
        run: |
          ls -l $RUNNER_TOOL_CACHE/Python/3.13.*/x64

      - if: matrix.os == 'windows-2022'
        name: Setup python3.13 on Windows
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - if: matrix.os == 'windows-2022'
        name: on Windows
        run: |
          ls -l $Env:RUNNER_TOOL_CACHE\python\3.13.*\x64

