on:
  push:
    branches:
      - github_actions_debug

jobs:
  check:
    name: Check per OS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: check chmod
        shell: pwsh
        run: |
          New-Item -Path . -Name "script.py" -ItemType "file"
          if ("${{ matrix.os }}" -ne "windows-2022") {
            echo "Not on Windows"
            chmod a+x script.py
          } else {
            echo "On Windows"
          }

  test:
    name: Test per OS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-2022]
      fail-fast: false
    uses: ./.github/workflows/test.yaml
    with:
      runs-on_value: ${{ matrix.os }}
      artifacts_version: f6c4a8b44ff3b87bc7ff04b88921095d26bea155
      catboost_package_version: 1.2.5