name: Debug check

on:
  push:
    branches:
      - numpy_2

env:
  py_version_to_platform_subspec: |
    {
      "3.8": "cp38-cp38",
      "3.9": "cp39-cp39"
    }

jobs:
  check:
    name: Check Env
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo ${{ fromJSON(env.py_version_to_platform_subspec)["3.8"] }}

